# Configuration for function minimization example
max_iterations: 500
checkpoint_interval: 10
early_stopping_metric: "combined_score"  # Metric to track for early stopping

# LLM configuration
llm:
  primary_model: "qwen-plus-2025-07-28"# "gpt-3.5-turbo"
  primary_model_weight: 0.8
  secondary_model: "qwen-plus-2025-04-28"# "gpt-3.5-turbo"
  secondary_model_weight: 0.2
  temperature: 0.7
  # max_tokens: 32000
  timeout: 120

# Prompt configuration
prompt:
  system_message: "你是一位优秀的数据专家.你的任务是从数据中寻找规律, 编写代码, 判断数据是否有正常. 返回 True 表示正常, 返回 False 表示不正常. 注意: 你只能看到正常数据, 所有请尽力总结正常规律, 这样有利于发现异常,从而获得更高的分数"

# Database configuration
database:
  population_size: 50
  archive_size: 20
  num_islands: 3
  elite_selection_ratio: 0.2
  exploitation_ratio: 0.7

# Evaluator configuration
evaluator:
  timeout: 60
  cascade_evaluation: false
  # cascade_thresholds: [1.3]
  # parallel_evaluations: 3

# Evolution settings
diff_based_evolution: true
max_code_length: 20000